### ISSUE TITLE
Data path "" should NOT have additional properties(project).

### ISSUE THREAD

**Issue by s0ftimage** [jaxuk/dnn_OpenNewsSPA_Admin#1]
I am anxious to see this module work.  Can you please tell me what this error mean?

C:\node\dnn_OpenNewsSPA_Admin-master>ng serve
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(project).
Error: Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(project).
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (C:\node\dnn_OpenNewsSPA_Admin-master\node_modules\@angular-devkit\core\src\workspace\workspace.js:173:42)
    at MergeMapSubscriber._tryNext (C:\node\dnn_OpenNewsSPA_Admin-master\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\mergeMap.js:122:27)
    at MergeMapSubscriber._next (C:\node\dnn_OpenNewsSPA_Admin-master\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (C:\node\dnn_OpenNewsSPA_Admin-master\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (C:\node\dnn_OpenNewsSPA_Admin-master\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\mergeMap.js:141:26)
    at InnerSubscriber._next (C:\node\dnn_OpenNewsSPA_Admin-master\node_modules\@angular-devkit\core\node_modules\rxjs\internal\InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (C:\node\dnn_OpenNewsSPA_Admin-master\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:103:18)
    at MapSubscriber._next (C:\node\dnn_OpenNewsSPA_Admin-master\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\map.js:92:26)
    at MapSubscriber.Subscriber.next (C:\node\dnn_OpenNewsSPA_Admin-master\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:103:18)
    at SwitchMapSubscriber.notifyNext (C:\node\dnn_OpenNewsSPA_Admin-master\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\switchMap.js:122:26)

**Comment by jaxuk** [comment]
Like I said before this isn't ready yet. I will update github this week
with a more recent work in progress that you can try out with some minimum
requirements.

Whatever you do. Do NOT install this in a production environment as this is
still in development
